apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: centos-image
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    generation: 1
    labels:
      app: centos-image
    name: centos-image
    namespace: openshift    
  spec:
    lookupPolicy:
      local: false
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: centos-image
    name: centos-image
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: centos-image:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: git@github.com:abavage/centos-image
      sourceSecret:
        name: github-ssh
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: base-centos7:latest
          namespace: openshift
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: SOFbTqfumzyS6IIl1FQV
      type: GitHub
    - generic:
        secret: jr90eXl0G9y1V7Na-rwf
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
